var annotated_dup =
[
    [ "docstring", "namespacedocstring.html", [
      [ "PyClass", "classdocstring_1_1PyClass.html", "classdocstring_1_1PyClass" ]
    ] ],
    [ "pyexample", "namespacepyexample.html", [
      [ "PyClass", "classpyexample_1_1PyClass.html", "classpyexample_1_1PyClass" ]
    ] ],
    [ "__FlashStringHelper", "class____FlashStringHelper.html", null ],
    [ "A", "classA.html", "classA" ],
    [ "Afterdoc_Test", "classAfterdoc__Test.html", "classAfterdoc__Test" ],
    [ "Autolink_Test", "classAutolink__Test.html", "classAutolink__Test" ],
    [ "B", "classB.html", "classB" ],
    [ "C", "classC.html", "classC" ],
    [ "C1", "classC1.html", null ],
    [ "C2", "classC2.html", null ],
    [ "C3", "classC3.html", null ],
    [ "C4", "classC4.html", null ],
    [ "C5", "classC5.html", null ],
    [ "Car", "structCar.html", "structCar" ],
    [ "CoordStruct", "structCoordStruct.html", "structCoordStruct" ],
    [ "CryptnoxWallet", "classCryptnoxWallet.html", "classCryptnoxWallet" ],
    [ "CW_CardInfo", "structCW__CardInfo.html", "structCW__CardInfo" ],
    [ "CW_CryptoProvider", "classCW__CryptoProvider.html", "classCW__CryptoProvider" ],
    [ "CW_Logger", "classCW__Logger.html", "classCW__Logger" ],
    [ "CW_NfcTransport", "classCW__NfcTransport.html", "classCW__NfcTransport" ],
    [ "CW_Platform", "classCW__Platform.html", "classCW__Platform" ],
    [ "CW_SecureChannel", "classCW__SecureChannel.html", "classCW__SecureChannel" ],
    [ "CW_SecureSession", "structCW__SecureSession.html", "structCW__SecureSession" ],
    [ "CW_SignRequest", "structCW__SignRequest.html", "structCW__SignRequest" ],
    [ "CW_SignResult", "structCW__SignResult.html", "structCW__SignResult" ],
    [ "CW_Utils", "classCW__Utils.html", "classCW__Utils" ],
    [ "D", "classD.html", "classD" ],
    [ "E", "classE.html", null ],
    [ "Enum_Test", "classEnum__Test.html", "classEnum__Test" ],
    [ "Example_Test", "classExample__Test.html", "classExample__Test" ],
    [ "Fn_Test", "classFn__Test.html", "classFn__Test" ],
    [ "Include_Test", "classInclude__Test.html", "classInclude__Test" ],
    [ "Javadoc_Test", "classJavadoc__Test.html", "classJavadoc__Test" ],
    [ "Memgrp_Test", "classMemgrp__Test.html", "classMemgrp__Test" ],
    [ "mux_using_with", "classmux__using__with.html", "classmux__using__with" ],
    [ "Object", "structObject.html", "structObject" ],
    [ "Overload_Test", "classOverload__Test.html", "classOverload__Test" ],
    [ "Par_Test", "classPar__Test.html", null ],
    [ "QTstyle_Test", "classQTstyle__Test.html", "classQTstyle__Test" ],
    [ "SomeNiceClass", "classSomeNiceClass.html", null ],
    [ "String", "classString.html", "classString" ],
    [ "Tag", "classTag.html", "classTag" ],
    [ "Test", "classTest.html", "classTest" ],
    [ "Test&lt; T * &gt;", "classTest_3_01T_01_5_01_4.html", "classTest_3_01T_01_5_01_4" ],
    [ "Test&lt; void *, 200 &gt;", "classTest_3_01void_01_5_00_01200_01_4.html", "classTest_3_01void_01_5_00_01200_01_4" ],
    [ "Truck", "structTruck.html", "structTruck" ],
    [ "Vehicle", "structVehicle.html", "structVehicle" ]
];